// Routes for /api/dq — Data Quality issues (log_dq_issue). These rows are
// generated by generateDQ() in appointments.js whenever an appointment is
// created/edited/imported (e.g. missing report date, overlapping auditors).
// This file only lists and resolves/waives them — it never creates them.
const router = require('express').Router();
const db     = require('../config/db');

// GET /api/dq — list open DQ issues, optionally filtered by severity/type/
// fy_id/company_id. Used by the Data Quality screen.
router.get('/', async (req, res) => {
  try {
    const { severity='', type='', fy_id='', company_id='' } = req.query;
    const params = []; let where = "WHERE dq.status='open'";
    if (severity)   { where += ' AND dq.severity=?';   params.push(severity); }
    if (type)       { where += ' AND dq.issue_type=?';  params.push(type); }
    if (fy_id)      { where += ' AND dq.fy_id=?';       params.push(fy_id); }
    if (company_id) { where += ' AND dq.company_id=?';  params.push(company_id); }
    const [rows] = await db.query(`
      SELECT dq.*, cm.co_name, fy.fy_label
      FROM log_dq_issue dq
      JOIN ma_company cm ON cm.company_id = dq.company_id
      JOIN ma_fy fy      ON fy.fy_id      = dq.fy_id
      ${where}
      ORDER BY FIELD(dq.severity,'error','warning','info'), cm.co_name
    `, params);
    res.json(rows);
  } catch(e) { res.status(500).json({ error: e.message }); }
});

// PUT /api/dq/:id/resolve — mark an issue as resolved (no reason given) or
// waived (waive_reason supplied). Called from the "Resolve"/"Waive" buttons
// on the Data Quality screen.
router.put('/:id/resolve', async (req, res) => {
  try {
    const { waive_reason } = req.body;
    const action = waive_reason ? 'waived' : 'resolved';
    // UPDATE: close out the DQ issue row
    await db.query(
      `UPDATE log_dq_issue SET status=?, resolved_at=NOW(), waive_reason=? WHERE dq_issue_id=?`,
      [action, waive_reason||null, req.params.id]);
    res.json({ ok: true });
  } catch(e) { res.status(500).json({ error: e.message }); }
});

module.exports = router;